// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xcrqifusfscczksptqyw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhjcnFpZnVzZnNjY3prc3B0cXl3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc1NDI5NjYsImV4cCI6MjA3MzExODk2Nn0.a74y2JX9aNSZfeu3X5rp27DxQ-fit4OPANA11smBxeo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});